## Describe the bug
I want to find the error in error.py

# Error

```NameError: name 'some_variable' is not defined
```
